export const mock_Roles = [
  "System Admin",
  "System Guest",
  "System User",
 ];
export const mock_Status = [
  "Active",
  "Pending",
  "Processing",
  "Rejected",
  "Delayed",
  "Created",
  "Completed",
  "Approved",
  "Cancelled",
  "On Hold",
  "In Progress",
  "Submitted",
  "Under Review",
  "Failed",
  "Scheduled",
  "Deferred",
  "Closed",
  "Reopened",
  "Inactive",
  "Expired",
  "Deleted",
  "Suspended",
  "Banned",
  "Draft",
  "Archived",
  "Escalated",
  "Awaiting Feedback",
  "Partially Completed",
  "Accepted",
  "Declined",
];
export const mock_Menus = [
  "useraccess_screen",
  "system_admin_dashboard",
  "guest_dashboard",
  "system_user_dashboard"
];
